### PR TITLE
Dep 2936

### PR DESCRIPTION
**Pull request by ngoziharrison**

### CODE REVIEW

**Comment by kirschbombe** [comment]
Hi, @ngoziharrison - can we split this into two separate PRs? I want to merge in the folders and the script updates, but I'm not ready to merge in the "batch 1" work - which is a separate ticket, and I think needs more work before we merge it in.

**Comment by kirschbombe** [comment]
I just noticed there is already a PR and branch for the "split need-dim csv files into batches...", so we shouldn't have those commits in both branches/PRs. Also, for the batch 1 files, the completed files are in the top level directory in the repo. I would expect that the batch folder would move from the needs-dims folder to the ready to festerize folder. Can you fix that? I made some comments in the Jira ticket re: the errors, so be sure to read those.

**Comment by ngoziharrison** [comment]
Hey Dawn, I think the reason it happened like this is because I made a branch on the previous branch and made an update to the script that I needed for the batch 1 work but didn't want to hold up working while waiting for the pull request to get merged in. Will fix the issues that you highlighted for batch 1 then will update push so we can get everything cleaned up

**Comment by kirschbombe** [comment]
Ah, that makes, sense. I did go ahead and merge the folders PR.

**Comment by ngoziharrison** [comment]
Quick note on the batch script, I didn't make it automatically put the finished csv files in the ready to festerize folder because I thought it might be good to review them first in the top level directory so you could easily see what was recently finished then move to the folder manually. Let me know if this is okay or you want them to go in the folder automatically

**Comment by kirschbombe** [comment]
I don't think the script needs to put them in the folder, but who ever is doing the batch should make sure they are moved to the ready for fester folder before pushing. I'd prefer not to to have orphan files at the top level. I think the files should stay in their batch folder all the way through the process, so it could save the files in the current needs-dims folder, then the person moves that completed folder, or whatever works best. I don't think we need to script everything, but we do need to keep the files organized since multiple people will be working on them and it would get very messy otherwise.

**Comment by ngoziharrison** [comment]
Just finished running the script again and no errors this time so looks like it was a good idea to re run. I checked and the only csv's it made changes to this time were the csv's that had errors reported in errors.csv

**Comment by kirschbombe** [comment]
@ngoziharrison - seems like we're getting closer to an efficient system, so thank you! I'm going to merge these in now, but for next time, can you keep the files from a batch together in a batch folder? so if you are working with a "batch2" folder in need-dims, then once finished, there should be a "batch2" folder in the ready for fester folder with all the updated CSVs for that batch. And we also need to delete the old CSVs in the need-dims folder so we don't have duplicate, but divergent CSVs here. For this batch, I will put them in a "batch1" folder, so you don't need to do that.

**Pull request merged**
